// <auto-generated />
using System;
using CargoHub;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CargoHub.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241110152754_BaseModel")]
    partial class BaseModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("CargoHub.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("CargoHub.ItemGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ItemGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 11, 10, 15, 27, 54, 612, DateTimeKind.Utc).AddTicks(7233),
                            Description = "Items related to electronic devices and accessories.",
                            Name = "Electronics",
                            UpdatedAt = new DateTime(2024, 11, 10, 15, 27, 54, 612, DateTimeKind.Utc).AddTicks(7235)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 11, 10, 15, 27, 54, 612, DateTimeKind.Utc).AddTicks(7237),
                            Description = "Items for home and office furniture.",
                            Name = "Furniture",
                            UpdatedAt = new DateTime(2024, 11, 10, 15, 27, 54, 612, DateTimeKind.Utc).AddTicks(7237)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 11, 10, 15, 27, 54, 612, DateTimeKind.Utc).AddTicks(7239),
                            Description = "Items for writing, drawing, and office use.",
                            Name = "Stationery",
                            UpdatedAt = new DateTime(2024, 11, 10, 15, 27, 54, 612, DateTimeKind.Utc).AddTicks(7240)
                        });
                });

            modelBuilder.Entity("CargoHub.ItemLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemGroupId");

                    b.ToTable("ItemLines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 11, 10, 15, 27, 54, 612, DateTimeKind.Utc).AddTicks(7349),
                            Description = "High-performance laptop for work and gaming.",
                            ItemGroupId = 3,
                            Name = "Laptop",
                            UpdatedAt = new DateTime(2024, 11, 10, 15, 27, 54, 612, DateTimeKind.Utc).AddTicks(7350)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 11, 10, 15, 27, 54, 612, DateTimeKind.Utc).AddTicks(7352),
                            Description = "Ergonomic chair for comfortable seating during long hours.",
                            ItemGroupId = 3,
                            Name = "Office Chair",
                            UpdatedAt = new DateTime(2024, 11, 10, 15, 27, 54, 612, DateTimeKind.Utc).AddTicks(7352)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 11, 10, 15, 27, 54, 612, DateTimeKind.Utc).AddTicks(7354),
                            Description = "Lined notebook for taking notes and organizing tasks.",
                            ItemGroupId = 3,
                            Name = "Notebook",
                            UpdatedAt = new DateTime(2024, 11, 10, 15, 27, 54, 612, DateTimeKind.Utc).AddTicks(7355)
                        });
                });

            modelBuilder.Entity("CargoHub.ItemType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemLineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemLineId");

                    b.ToTable("ItemType");
                });

            modelBuilder.Entity("CargoHub.Models.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Province")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "updated_at");

                    b.Property<string>("Zip")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContactId")
                        .IsUnique();

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("CargoHub.ItemLine", b =>
                {
                    b.HasOne("CargoHub.ItemGroup", "ItemGroup")
                        .WithMany("ItemLines")
                        .HasForeignKey("ItemGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemGroup");
                });

            modelBuilder.Entity("CargoHub.ItemType", b =>
                {
                    b.HasOne("CargoHub.ItemLine", "ItemLine")
                        .WithMany("ItemTypes")
                        .HasForeignKey("ItemLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemLine");
                });

            modelBuilder.Entity("CargoHub.Models.Warehouse", b =>
                {
                    b.HasOne("CargoHub.Contact", "Contact")
                        .WithOne()
                        .HasForeignKey("CargoHub.Models.Warehouse", "ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("CargoHub.ItemGroup", b =>
                {
                    b.Navigation("ItemLines");
                });

            modelBuilder.Entity("CargoHub.ItemLine", b =>
                {
                    b.Navigation("ItemTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
