GET http://localhost:3000/api/v2/ItemGroups?Id=4
#####
GET http://localhost:3000/api/v2/ItemGroups?Id=4
ApiKey: 
####
GET http://localhost:3000/api/v2/ItemGroups?Id=4
ApiKey: "Invalid"
####
GET http://localhost:3000/api/v2/Orders?Id=1
ApiKey: WHM
####
GET http://localhost:3000/api/v2/warehouse?Id=1
ApiKey: FM
###
GET http://localhost:3000/api/v2/warehouse?Id=1
ApiKey: SP
