@baseUrl = http://localhost:3000/api/v2/inventories

###
POST {{baseUrl}}
Content-Type: application/json

{
    "itemId": "123141233",
    "description": "RandomDescription",
    "itemReference": "REF456",
    "locations": [
        101, 
        102, 
        103
    ],
    "totalOnHand": 50,
    "totalExpected": 20,
    "totalOrdered": 30,
    "totalAllocated": 10,
    "totalAvailable": 40,
    "createdAt": "2024-11-10T12:00:00Z",
    "updatedAt": "2024-11-10T12:00:00Z"
}

###

PUT {{baseUrl}}/2
Content-Type: application/json

{
    "id": 2,
    "itemId": "987987",
    "description": "RandomDescription2",
    "itemReference": "REF456",
    "locations": [
        101, 
        102, 
        103
    ],
    "totalOnHand": 50,
    "totalExpected": 20,
    "totalOrdered": 30,
    "totalAllocated": 10,
    "totalAvailable": 40
}

###

DELETE {{baseUrl}}/1

###
GET {{baseUrl}}/2

###
GET {{baseUrl}}