GET http://localhost:3000/api/v1/ItemLines?Id=2
####
GET http://localhost:3000/api/v1/ItemLines/GetMultiple?Ids=1&Ids=2&Ids=3&Ids=7
####
POST http://localhost:3000/api/v1/ItemLines
Content-Type: application/json


{
    "Id": 4,
    "Name": "No name",
    "Description": "No Description"
}
###
PUT http://localhost:3000/api/v1/ItemLines?Id=4
Content-Type: application/json

{
    "Id": 4,
    "Name": "Desk Lamp",
    "Description": "Adjustable LED desk lamp with brightness settings."
}

####
DELETE http://localhost:3000/api/v1/ItemLines/Delete?Id=4


