### Get Locations by ID
GET http://localhost:3000/api/v2/Locations/3
Content-Type: application/json
ApiKey: Admin

### Get Locationss
GET http://localhost:3000/api/v2/locations?page=0
Content-Type: application/json
ApiKey: Admin

### Get Locationss in a Warehouse
GET http://localhost:3000/api/v2/Locations/warehouse/1
Content-Type: application/json
ApiKey: Admin

### Add a New Locations
POST http://localhost:3000/api/v2/Locations
Content-Type: application/json
ApiKey: Admin

{
    "WarehouseId": 1,
    "Code": "LOC001",
    "Name": "Main Storage"
}

### Update an Existing Locations
PUT http://localhost:3000/api/v2/Locations/1
Content-Type: application/json
ApiKey: Admin

{
    "WarehouseId": 1,
    "Code": "LOC001h_UPDATED",
    "Name": "Main Storagge Updated"
}

### Remove a Locations
DELETE http://localhost:3000/api/v2/Locations/1
Content-Type: application/json
ApiKey: Admin
