### Create a new location
POST http://localhost:3000/api/v1/locations
Content-Type: application/json
ApiKey: Admin

{
  "warehouseId": 1,  // The warehouse the location belongs to, null if no warehouse
  "code": "LOC001",
  "name": "Location 1",
  "createdAt": "2024-11-18T00:00:00",
  "updatedAt": "2024-11-18T00:00:00"
}

POST http://localhost:3000/api/v1/locations
Content-Type: application/json
ApiKey: Admin

{
  "warehouseId": 2,  // The warehouse the location belongs to, null if no warehouse
  "code": "LOC001",
  "name": "Location 1",
  "createdAt": "2024-11-18T00:00:00",
  "updatedAt": "2024-11-18T00:00:00"
}

### Get all locations
GET http://localhost:3000/api/v1/locations
ApiKey: Admin

### Get location by id
GET http://localhost:3000/api/v1/locations/{id}
ApiKey: Admin

### Update location by id
PUT http://localhost:3000/api/v1/locations/{id}
Content-Type: application/json
ApiKey: Admin

{
  "warehouseId": 2,  // Updated warehouse ID or null if no warehouse
  "code": "LOC002",
  "name": "Location 2",
  "createdAt": "2024-11-18T00:00:00",
  "updatedAt": "2024-11-18T00:00:00"
}

### Delete location by id
DELETE http://localhost:3000/api/v1/locations/{id}
ApiKey: Admin
